/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables.records;


import java.math.BigDecimal;
import java.time.LocalDateTime;

import jooqdata.tables.Lot;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LotRecord extends UpdatableRecordImpl<LotRecord> implements Record7<String, String, BigDecimal, String, String, String, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>purchase.lot.lot_name</code>.
     */
    public LotRecord setLotName(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>purchase.lot.lot_name</code>.
     */
    public String getLotName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>purchase.lot.customer_code</code>.
     */
    public LotRecord setCustomerCode(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>purchase.lot.customer_code</code>.
     */
    public String getCustomerCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>purchase.lot.price</code>.
     */
    public LotRecord setPrice(BigDecimal value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>purchase.lot.price</code>.
     */
    public BigDecimal getPrice() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>purchase.lot.currency_code</code>.
     */
    public LotRecord setCurrencyCode(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>purchase.lot.currency_code</code>.
     */
    public String getCurrencyCode() {
        return (String) get(3);
    }

    /**
     * Setter for <code>purchase.lot.nds_rate</code>.
     */
    public LotRecord setNdsRate(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>purchase.lot.nds_rate</code>.
     */
    public String getNdsRate() {
        return (String) get(4);
    }

    /**
     * Setter for <code>purchase.lot.place_delivery</code>.
     */
    public LotRecord setPlaceDelivery(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>purchase.lot.place_delivery</code>.
     */
    public String getPlaceDelivery() {
        return (String) get(5);
    }

    /**
     * Setter for <code>purchase.lot.date_delivery</code>.
     */
    public LotRecord setDateDelivery(LocalDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>purchase.lot.date_delivery</code>.
     */
    public LocalDateTime getDateDelivery() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<String, String, BigDecimal, String, String, String, LocalDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<String, String, BigDecimal, String, String, String, LocalDateTime> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Lot.LOT.LOT_NAME;
    }

    @Override
    public Field<String> field2() {
        return Lot.LOT.CUSTOMER_CODE;
    }

    @Override
    public Field<BigDecimal> field3() {
        return Lot.LOT.PRICE;
    }

    @Override
    public Field<String> field4() {
        return Lot.LOT.CURRENCY_CODE;
    }

    @Override
    public Field<String> field5() {
        return Lot.LOT.NDS_RATE;
    }

    @Override
    public Field<String> field6() {
        return Lot.LOT.PLACE_DELIVERY;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return Lot.LOT.DATE_DELIVERY;
    }

    @Override
    public String component1() {
        return getLotName();
    }

    @Override
    public String component2() {
        return getCustomerCode();
    }

    @Override
    public BigDecimal component3() {
        return getPrice();
    }

    @Override
    public String component4() {
        return getCurrencyCode();
    }

    @Override
    public String component5() {
        return getNdsRate();
    }

    @Override
    public String component6() {
        return getPlaceDelivery();
    }

    @Override
    public LocalDateTime component7() {
        return getDateDelivery();
    }

    @Override
    public String value1() {
        return getLotName();
    }

    @Override
    public String value2() {
        return getCustomerCode();
    }

    @Override
    public BigDecimal value3() {
        return getPrice();
    }

    @Override
    public String value4() {
        return getCurrencyCode();
    }

    @Override
    public String value5() {
        return getNdsRate();
    }

    @Override
    public String value6() {
        return getPlaceDelivery();
    }

    @Override
    public LocalDateTime value7() {
        return getDateDelivery();
    }

    @Override
    public LotRecord value1(String value) {
        setLotName(value);
        return this;
    }

    @Override
    public LotRecord value2(String value) {
        setCustomerCode(value);
        return this;
    }

    @Override
    public LotRecord value3(BigDecimal value) {
        setPrice(value);
        return this;
    }

    @Override
    public LotRecord value4(String value) {
        setCurrencyCode(value);
        return this;
    }

    @Override
    public LotRecord value5(String value) {
        setNdsRate(value);
        return this;
    }

    @Override
    public LotRecord value6(String value) {
        setPlaceDelivery(value);
        return this;
    }

    @Override
    public LotRecord value7(LocalDateTime value) {
        setDateDelivery(value);
        return this;
    }

    @Override
    public LotRecord values(String value1, String value2, BigDecimal value3, String value4, String value5, String value6, LocalDateTime value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LotRecord
     */
    public LotRecord() {
        super(Lot.LOT);
    }

    /**
     * Create a detached, initialised LotRecord
     */
    public LotRecord(String lotName, String customerCode, BigDecimal price, String currencyCode, String ndsRate, String placeDelivery, LocalDateTime dateDelivery) {
        super(Lot.LOT);

        setLotName(lotName);
        setCustomerCode(customerCode);
        setPrice(price);
        setCurrencyCode(currencyCode);
        setNdsRate(ndsRate);
        setPlaceDelivery(placeDelivery);
        setDateDelivery(dateDelivery);
    }

    /**
     * Create a detached, initialised LotRecord
     */
    public LotRecord(jooqdata.tables.pojos.Lot value) {
        super(Lot.LOT);

        if (value != null) {
            setLotName(value.getLotName());
            setCustomerCode(value.getCustomerCode());
            setPrice(value.getPrice());
            setCurrencyCode(value.getCurrencyCode());
            setNdsRate(value.getNdsRate());
            setPlaceDelivery(value.getPlaceDelivery());
            setDateDelivery(value.getDateDelivery());
        }
    }
}
